version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: housy
    ports:
      - 5432:5432
    volumes:
      - /home/ubuntu/pgsql/data:/var/lib/postgresql/data/